services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssqlserver
    ports:
      - "1433:1433"
    volumes:
      - ./mssql_data:/var/opt/mssql
    environment:
      SA_PASSWORD: "mssqlpassword2025"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
